spellcheck: Add spelling linter
security-summer-school/actions pull request #4
Opened 2023-07-28 09:01 UTC by mariasfiraiala

This is an attempt at adding a spell checker to the available actions. @gabrielmocanu You might find [the pattern for finding the md files](https://github.com/mariasfiraiala/actions/blob/9d7c7281d7eefe42fef5954127c6d8700d96e9bb/spellcheck/config/spellcheck.yml#L14) wrong. Apologies for that, I don't really have the means of testing this PR.

2023-07-28 23:11 UTC, gabrielmocanu requested changes
I don't think this path [1] will work, but we can test this after merging this PR.

[1]: https://github.com/security-summer-school/actions/pull/4/files#diff-6d93f5a4f7cde7d4e801ac15bc053890474f1aa9dc67cad6c9c7de45868989e6R17

2023-07-28 23:11 UTC, gabrielmocanu commented on spellcheck/action.yml
> +        task_name: Markdown
```suggestion
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Spellcheck
      uses: rojopolis/spellcheck-github-actions@0.33.1
      with:
        config_path: config/spellcheck.yml
        task_name: Markdown
```

2023-07-29 01:14 UTC, teodutu commented
@mariasfiraiala you can test this before merging. Just create a repo, add this action, then raise a PR in that repo. If the action runs fine, paste a link to the run here and we'll know the config is good.

2023-07-29 06:39 UTC, mariasfiraiala commented
@gabrielmocanu The path does not work, indeed. I've tested a couple of variations with it and I can't pin point exactly what's wrong. Any ideas?

2023-07-29 10:34 UTC, mariasfiraiala commented
Manged to fix the config path problem. Tested it on [my repo](https://github.com/mariasfiraiala/essentials/actions/runs/5699873144/job/15449208485?pr=2), works like a charm. @gabrielmocanu Please take another look if possible

2023-07-30 09:25 UTC, gabrielmocanu approved these changes
Let's see how it's working.

2023-07-30 09:25 UTC, merged